# Javascript Node CircleCI 2.0 configuration file.
# Check https://circleci.com/docs/2.0/language-javascript/ for more details.
#
version: 2
jobs:
  build:
    docker:
      # Set the Node.js version we are working with.
      - image: circleci/node:8.9.0

    # Working directory, corresponds to the repository name
    # which gets checked out to the home folder (~).
    working_directory: ~/places

    steps:
      - checkout

      # Download and cache dependencies.
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Fetch dependencies and build binaries.
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run test suite for ALL branches.
      - run: yarn test

      # All commits to master trigger a deploy of the webapp to production.
      - deploy:
          name: Build and deploy master branch to the production environment
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  yarn build
                  # https://surge.sh/help/adding-a-200-page-for-client-side-routing
                  cp build/index.html build/200.html
                  ./node_modules/.bin/surge --project ./build --domain https://places.fknussel.com
              else
                  echo "Not master branch so not deploying"
              fi
